"use client";
import { useMemo, useState } from "react";
import { createMatch, saveMatch, deleteMatch } from "./actions";
import { eligiblePlayers, isIncreasing, selectPlayer } from "./lineup-order";
export type TeamRow={id:string;name:string;division:number|null};
export type MatchRow={id:string;season_id:string;team_id:string;team_name:string;opponent_name:string;division:number;phase:string;round_label:string;is_home:boolean;original_at:string|Date;scheduled_at:string|Date;venue:string|null;status:string};
export type PlayerRow={team_id:string;phase:string;id:string;name:string;position:number};
export type GameRow={match_id:string;position:number;player_id:string;player_name:string;opponent_player_name:string|null;local_caroms:number|null;opponent_caroms:number|null;local_innings:number|null;opponent_innings:number|null};
type Filter="all"|"today"|"week"|"month"|"range";
const hours=Array.from({length:24},(_,i)=>String(i).padStart(2,"0"));
const minutes=["00","15","30","45"];
function parts(date:string|Date){const p=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Lisbon",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(date));const get=(key:string)=>p.find(x=>x.type===key)?.value??"";return {date:`${get("day")}/${get("month")}/${get("year")}`,hour:get("hour"),minute:get("minute"),day:`${get("year")}-${get("month")}-${get("day")}`};}
function dateKey(date:string|Date){return parts(date).day;}
function todayKey(){return dateKey(new Date());}
function addDays(key:string,days:number){const [y,m,d]=key.split("-").map(Number);const x=new Date(Date.UTC(y,m-1,d+days));return x.toISOString().slice(0,10);}
function labelDate(key:string){if(!key)return "";const [y,m,d]=key.split("-");return `${d}/${m}/${y}`;}
function FilterDate({label,value,onChange,min}:{label:string;value:string;onChange:(value:string)=>void;min?:string}){return <div className="flex items-end gap-2"><label className="text-sm">{label} (dd/mm/aaaa)<input readOnly value={labelDate(value)} placeholder="dd/mm/aaaa" className="mt-1 block h-10 w-32 rounded-lg border bg-white px-2"/></label><label className="text-sm">Calendário<input type="date" lang="pt-PT" aria-label={`Selecionar data ${label.toLowerCase()}`} value={value} min={min} onChange={e=>onChange(e.target.value)} className="mt-1 block h-10 w-12 rounded-lg border bg-white text-transparent"/></label></div>}
function DateInput({initial}:{initial?:string|Date}){
 const [date,setDate]=useState(initial?parts(initial).date:"");
 return <div className="flex items-end gap-2"><label className="min-w-0 flex-1 text-sm">Data (dd/mm/aaaa)<input name="date" required value={date} onChange={e=>setDate(e.target.value)} inputMode="numeric" placeholder="dd/mm/aaaa" pattern="[0-9]{2}/[0-9]{2}/[0-9]{4}" className="mt-1 h-10 w-full rounded-lg border px-2"/></label><label className="text-sm">Calendário<input type="date" lang="pt-PT" aria-label="Selecionar data no calendário" value={/^\d{2}\/\d{2}\/\d{4}$/.test(date)?`${date.slice(6)}-${date.slice(3,5)}-${date.slice(0,2)}`:""} onChange={e=>setDate(labelDate(e.target.value))} className="mt-1 block h-10 w-12 rounded-lg border bg-white text-transparent"/></label></div>;
}
function TimeInput({initial}:{initial?:string|Date}){const time=initial?parts(initial):null;return <div className="grid grid-cols-2 gap-2"><label className="text-sm">Hora<select name="hour" required defaultValue={time?.hour??""} className="mt-1 h-10 w-full rounded-lg border bg-white px-2"><option value="" disabled>HH</option>{hours.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="text-sm">Minutos<select name="minute" required defaultValue={time&&minutes.includes(time.minute)?time.minute:""} className="mt-1 h-10 w-full rounded-lg border bg-white px-2"><option value="" disabled>MM</option>{minutes.map(x=><option key={x} value={x}>{x}</option>)}</select></label>{time&&!minutes.includes(time.minute)&&<p className="col-span-2 text-xs">Hora anterior {time.hour}:{time.minute}; escolhe um dos intervalos de 15 minutos.</p>}</div>}
function NewMatch({seasonId,teams,close}:{seasonId:string;teams:TeamRow[];close:()=>void}){return <form action={createMatch} className="space-y-3 p-5"><input type="hidden" name="seasonId" value={seasonId}/><label className="block text-sm">Equipa<select name="teamId" required className="mt-1 h-10 w-full rounded-lg border bg-white px-2">{teams.filter(t=>t.division!==null).map(t=><option key={t.id} value={t.id}>{t.name} · {t.division}.ª divisão</option>)}</select></label><label className="block text-sm">Adversário<input name="opponent" required minLength={2} maxLength={120} className="mt-1 h-10 w-full rounded-lg border px-2"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Fase<select name="phase" className="mt-1 h-10 w-full rounded-lg border bg-white px-2"><option value="first_leg">1.ª volta</option><option value="second_leg">2.ª volta</option><option value="qualification">Apuramento</option></select></label><label className="text-sm">Jornada<input name="round" required maxLength={80} className="mt-1 h-10 w-full rounded-lg border px-2"/></label><div className="grid gap-3 sm:col-span-2 sm:grid-cols-[minmax(220px,1.5fr)_minmax(160px,1fr)_minmax(180px,1fr)]"><DateInput/><TimeInput/><label className="text-sm">Local<input name="venue" maxLength={120} className="mt-1 h-10 w-full rounded-lg border px-2"/></label></div><label className="text-sm">Casa/fora<select name="home" className="mt-1 h-10 w-full rounded-lg border bg-white px-2"><option value="true">Casa</option><option value="false">Fora</option></select></label></div><div className="flex justify-end gap-2"><button type="button" onClick={close} className="rounded-lg border px-4 py-2">Cancelar</button><button className="rounded-lg bg-[var(--club-green-700)] px-4 py-2 text-white">Gravar</button></div></form>}
function EditMatch({match,games,players,teams,close}:{match:MatchRow;games:GameRow[];players:PlayerRow[];teams:TeamRow[];close:()=>void}){
 const [teamId,setTeamId]=useState(match.team_id);
 const [phase,setPhase]=useState(match.phase);
 const roster=players.filter(p=>p.team_id===teamId&&p.phase===phase)
   .sort((a,b)=>Number(a.position)-Number(b.position));
 const [selected,setSelected]=useState<string[]>([0,1,2,3].map(i=>games.find(g=>g.position===i+1)?.player_id??""));
 return <form action={saveMatch} className="space-y-4 p-5"><input type="hidden" name="matchId" value={match.id}/><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Equipa<select name="teamId" required value={teamId} onChange={e=>{setTeamId(e.target.value);setSelected(["","","",""])}} className="mt-1 h-10 w-full rounded-lg border bg-white px-2">{teams.filter(t=>t.division!==null).map(t=><option key={t.id} value={t.id}>{t.name} · {t.division}.ª divisão</option>)}</select></label><label className="text-sm">Adversário<input name="opponent" required minLength={2} maxLength={120} defaultValue={match.opponent_name} className="mt-1 h-10 w-full rounded-lg border px-2"/></label><div className="grid gap-3 sm:col-span-2 sm:grid-cols-[minmax(220px,1.5fr)_minmax(160px,1fr)_minmax(180px,1fr)]"><DateInput initial={match.scheduled_at}/><TimeInput initial={match.scheduled_at}/><label className="text-sm">Local<input name="venue" maxLength={120} defaultValue={match.venue??""} className="mt-1 h-10 w-full rounded-lg border px-2"/></label></div></div><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Fase<select name="phase" value={phase} onChange={e=>{setPhase(e.target.value);setSelected(["","","",""])}} className="mt-1 h-10 w-full rounded-lg border bg-white px-2"><option value="first_leg">1.ª volta</option><option value="second_leg">2.ª volta</option><option value="qualification">Apuramento</option></select></label><label className="text-sm">Jornada<input name="round" required maxLength={80} defaultValue={match.round_label} className="mt-1 h-10 w-full rounded-lg border px-2"/></label><label className="text-sm">Casa/fora<select name="home" defaultValue={String(match.is_home)} className="mt-1 h-10 w-full rounded-lg border bg-white px-2"><option value="true">Casa</option><option value="false">Fora</option></select></label></div><p className="text-xs text-slate-600">Data inicial: {parts(match.original_at).date}</p>
 <div className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left text-sm"><thead><tr className="border-b"><th className="p-2">Pos.</th><th className="p-2">Jogador da equipa</th><th className="p-2">Adversário</th><th className="p-2">Bolas nossas</th><th className="p-2">Entradas nossas</th><th className="p-2">Bolas adversário</th><th className="p-2">Entradas adversário</th></tr></thead><tbody>{[0,1,2,3].map(i=>{const game=games.find(g=>g.position===i+1);return <tr key={i} className="border-b"><td className="p-2">{i+1}</td><td className="p-1"><select name={`player${i+1}`} value={selected[i]} onChange={e=>setSelected(current=>selectPlayer(roster,current,i,e.target.value))} className="w-full rounded border p-2"><option value="">Selecionar</option>{eligiblePlayers(roster,selected,i).map(p=><option key={p.id} value={p.id}>{Number(p.position)}. {p.name}</option>)}</select></td><td className="p-1"><input name={`opponentPlayer${i+1}`} defaultValue={game?.opponent_player_name??""} maxLength={120} placeholder="Nome" className="w-full rounded border p-2"/></td>{([['localCaroms',game?.local_caroms,0],['localInnings',game?.local_innings,1],['opponentCaroms',game?.opponent_caroms,0],['opponentInnings',game?.opponent_innings,1]] as const).map(([key,value,min])=><td key={key} className="p-1"><input type="number" name={`${key}${i+1}`} min={min} max={999} defaultValue={value??""} className="w-20 rounded border p-2"/></td>)}</tr>})}</tbody></table></div><p className="text-xs text-slate-600">Preenche os quatro valores numéricos de cada partida registada. Escolhe os jogadores pela ordem definida na equipa para esta fase. Podes saltar posições, mas não inverter a ordem. A convocatória pode ser alterada em qualquer momento.</p><div className="flex justify-end gap-2"><button type="button" onClick={close} className="rounded-lg border px-4 py-2">Cancelar</button><button disabled={!(selected.every(id=>!id) && games.length===0) && !isIncreasing(selected,roster)} className="rounded-lg bg-[var(--club-green-700)] px-4 py-2 text-white disabled:opacity-50">Gravar</button></div></form>
}
export function MatchesView({seasonId,admin,teams,matches,games,players,initialMatch,saveError}:{seasonId:string;admin:boolean;teams:TeamRow[];matches:MatchRow[];games:GameRow[];players:PlayerRow[];initialMatch:string;saveError:string}){
 const [filter,setFilter]=useState<Filter>("all"),[team,setTeam]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[modal,setModal]=useState<string|null>(matches.some(m=>m.id===initialMatch)?initialMatch:null),[deleting,setDeleting]=useState<string|null>(null);
 const now=todayKey(),last=addDays(now,6);
 const visible=useMemo(()=>matches.filter(m=>{const key=dateKey(m.scheduled_at);if(team&&m.team_id!==team)return false;if(filter==="today")return key===now;if(filter==="week")return key>=now&&key<=last;if(filter==="month")return key.slice(0,7)===now.slice(0,7);if(filter==="range")return (!start||key>=start)&&(!end||key<=end);return true;}),[matches,team,filter,now,last,start,end]);
 const chosen=matches.find(m=>m.id===modal);
 const close=()=>setModal(null);
 return <><section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div className="flex flex-wrap gap-2">{([['all','Todos'],['today','Hoje'],['week','Próximos 7 dias'],['month','Mês']] as const).map(([key,label])=><button type="button" key={key} onClick={()=>setFilter(key)} aria-pressed={filter===key} className={`rounded-lg border px-3 py-2 text-sm ${filter===key?"border-green-700 bg-green-50 font-semibold":""}`}>{label}</button>)}</div>{admin&&teams.some(t=>t.division!==null)&&<button onClick={()=>setModal("new")} className="rounded-lg bg-[var(--club-green-700)] px-4 py-2 text-sm text-white">Novo jogo</button>}</div><div className="mt-4 flex flex-wrap gap-3"><label className="text-sm">Equipa<select value={team} onChange={e=>setTeam(e.target.value)} className="ml-2 rounded-lg border bg-white p-2"><option value="">Todas</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{<><FilterDate label="Data início" value={start} onChange={value=>{setStart(value);setFilter("range");if(end&&value&&end<value)setEnd("")}}/><FilterDate label="Data fim" value={end} min={start||undefined} onChange={value=>{setEnd(value);setFilter("range")}}/></>}</div><p className="mt-3 text-xs text-slate-600">{visible.length} jogo(s) · horários de Lisboa · datas em dd/mm/aaaa</p><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[670px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">Data / hora</th><th className="p-3">Equipa</th><th className="p-3">Adversário</th><th className="p-3">Jornada</th><th className="p-3">Estado</th><th className="p-3">Ação</th></tr></thead><tbody>{visible.map(m=><tr key={m.id} className="border-b"><td className="p-3">{parts(m.scheduled_at).date} · {parts(m.scheduled_at).hour}:{parts(m.scheduled_at).minute}</td><td className="p-3">{m.team_name} · {m.division}.ª</td><td className="p-3">{m.opponent_name}</td><td className="p-3">{m.round_label}</td><td className="p-3">{m.status==="completed"?"Registado":"Agendado"}</td><td className="p-3"><div className="flex gap-1"><button type="button" onClick={()=>setModal(m.id)} className="rounded border px-2 py-1">{admin?"Editar":"Ver"}</button>{admin&&<button type="button" onClick={()=>setDeleting(m.id)} className="rounded border border-red-200 px-2 py-1 text-red-700">Eliminar</button>}</div></td></tr>)}</tbody></table>{visible.length===0&&<p className="p-5 text-sm text-slate-600">Sem jogos para estes filtros.</p>}</div></section>
 {deleting&&admin&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-3"><div role="alertdialog" aria-modal="true" aria-labelledby="delete-match-title" className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><h2 id="delete-match-title" className="text-lg font-semibold">Eliminar jogo</h2><p className="mt-3 text-sm">Eliminar {matches.find(m=>m.id===deleting)?.team_name} vs {matches.find(m=>m.id===deleting)?.opponent_name}? O jogo e as partidas associadas serão retirados das listagens; ficará um registo de auditoria.</p><form action={deleteMatch} className="mt-5 flex justify-end gap-2"><input type="hidden" name="matchId" value={deleting}/><button type="button" onClick={()=>setDeleting(null)} className="rounded border px-4 py-2">Cancelar</button><button type="submit" className="rounded bg-red-700 px-4 py-2 text-white">Eliminar</button></form></div></div>}
 {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-3" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div role="dialog" aria-modal="true" aria-labelledby="match-title" className="max-h-[92vh] w-full max-w-6xl overflow-y-auto rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b p-5"><h2 id="match-title" className="text-lg font-semibold">{modal==="new"?"Novo jogo":admin?"Editar jogo":"Detalhes do jogo"}</h2></div>{saveError&&<p role="alert" className="m-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{saveError}</p>}{modal==="new"?<NewMatch seasonId={seasonId} teams={teams} close={close}/>:chosen&&admin?<EditMatch key={chosen.id} match={chosen} games={games.filter(g=>g.match_id===chosen.id)} players={players} teams={teams} close={close}/>:chosen&&<div className="space-y-3 p-5 text-sm"><p>{chosen.team_name} vs {chosen.opponent_name} · {parts(chosen.scheduled_at).date} {parts(chosen.scheduled_at).hour}:{parts(chosen.scheduled_at).minute}</p>{games.filter(g=>g.match_id===chosen.id).map(g=><p key={g.position}>{g.position}.ª: {g.player_name} vs {g.opponent_player_name??"Por definir"} · bolas {g.local_caroms??"-"}:{g.opponent_caroms??"-"} · entradas {g.local_innings??"-"}:{g.opponent_innings??"-"}</p>)}<button type="button" onClick={close} className="rounded border px-4 py-2">Cancelar</button></div>}</div></div>}
 </>;
}
